<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>HOM_MEN_HOMARD</source>
      <translation>ロブスター</translation>
    </message>
    <message>
      <source>HOM_MEN_MODIFICATION</source>
      <translation>HOM_MEN_MODIFICATION</translation>
    </message>
    <message>
      <source>HOM_MEN_INFORMATION</source>
      <translation>HOM_MEN_INFORMATION</translation>
    </message>
    <message>
      <source>HOM_MEN_YACS</source>
      <translation>HOM_MEN_YACS</translation>
    </message>
    <message>
      <source>HOM_MEN_NEW_CASE</source>
      <translation>新しいケース</translation>
    </message>
    <message>
      <source>HOM_MEN_NEW_ITERATION</source>
      <translation>新しいイテレーション</translation>
    </message>
    <message>
      <source>HOM_MEN_PURSUE_ITERATION</source>
      <translation>HOM_MEN_PURSUE_ITERATION</translation>
    </message>
    <message>
      <source>HOM_MEN_COMPUTE</source>
      <translation>計算</translation>
    </message>
    <message>
      <source>HOM_MEN_EDIT</source>
      <translation>HOM_MEN_EDIT</translation>
    </message>
    <message>
      <source>HOM_MEN_DELETE</source>
      <translation>HOM_MEN_DELETE</translation>
    </message>
    <message>
      <source>HOM_MEN_MESH_INFO</source>
      <translation>HOM_MEN_MESH_INFO</translation>
    </message>
    <message>
      <source>HOM_MEN_EDIT_MESS_FILE</source>
      <translation>ファイルを表示します。</translation>
    </message>
    <message>
      <source>HOM_MEN_WRITE</source>
      <translation>HOM_MEN_WRITE</translation>
    </message>
    <message>
      <source>HOM_TOP_HOMARD</source>
      <translation>ロブスター</translation>
    </message>
    <message>
      <source>HOM_TOP_NEW_CASE</source>
      <translation>新しいケース</translation>
    </message>
    <message>
      <source>HOM_TOP_NEW_ITERATION</source>
      <translation>新しいイテレーション</translation>
    </message>
    <message>
      <source>HOM_TOP_PURSUE_ITERATION</source>
      <translation>HOM_TOP_PURSUE_ITERATION</translation>
    </message>
    <message>
      <source>HOM_TOP_COMPUTE</source>
      <translation>計算</translation>
    </message>
    <message>
      <source>HOM_TOP_EDIT</source>
      <translation>HOM_TOP_EDIT</translation>
    </message>
    <message>
      <source>HOM_TOP_DELETE</source>
      <translation>HOM_TOP_DELETE</translation>
    </message>
    <message>
      <source>HOM_TOP_EDIT_MESS_FILE</source>
      <translation>ファイルを表示します。</translation>
    </message>
    <message>
      <source>HOM_STB_HOMARD</source>
      <translation>ロブスター</translation>
    </message>
    <message>
      <source>HOM_STB_NEW_CASE</source>
      <translation>新しいケース</translation>
    </message>
    <message>
      <source>HOM_STB_NEW_ITERATION</source>
      <translation>新しいイテレーション</translation>
    </message>
    <message>
      <source>HOM_STB_PURSUE_ITERATION</source>
      <translation>HOM_STB_PURSUE_ITERATION</translation>
    </message>
    <message>
      <source>HOM_STB_COMPUTE</source>
      <translation>計算</translation>
    </message>
    <message>
      <source>HOM_STB_EDIT</source>
      <translation>HOM_STB_EDIT</translation>
    </message>
    <message>
      <source>HOM_STB_DELETE</source>
      <translation>HOM_STB_DELETE</translation>
    </message>
    <message>
      <source>HOM_STB_EDIT_MESS_FILE</source>
      <translation>ファイルを表示します。</translation>
    </message>
    <message>
      <source>HOM_WARNING</source>
      <translation>警告</translation>
    </message>
    <message>
      <source>HOM_ERROR</source>
      <translation>エラー</translation>
    </message>
    <message>
      <source>HOM_INACTIVE_BUTTON</source>
      <translation>アクティブでないボタン</translation>
    </message>
    <message>
      <source>HOM_SELECT_OBJECT_1</source>
      <translation>オブジェクトを選択します。</translation>
    </message>
    <message>
      <source>HOM_SELECT_OBJECT_2</source>
      <translation>1 つのオブジェクトを選択します。</translation>
    </message>
    <message>
      <source>HOM_SELECT_OBJECT_3</source>
      <translation>型 %1 のオブジェクトを選択します。</translation>
    </message>
    <message>
      <source>HOM_SELECT_FILE_1</source>
      <translation>ファイルを選択します。</translation>
    </message>
    <message>
      <source>HOM_SELECT_FILE_2</source>
      <translation>1 つのファイルを選択します。</translation>
    </message>
    <message>
      <source>HOM_SELECT_FILE_3</source>
      <translation>HOM_SELECT_FILE_3</translation>
    </message>
    <message>
      <source>HOM_SCRIPT_FILE</source>
      <translation>HOM_SCRIPT_FILE</translation>
    </message>
    <message>
      <source>HOM_MED_FILE_1</source>
      <translation>この医学ファイルは読み取り不可能です。</translation>
    </message>
    <message>
      <source>HOM_MED_FILE_2</source>
      <translation>この医学のファイルには、メッシュが含まれていません。</translation>
    </message>
    <message>
      <source>HOM_MED_FILE_3</source>
      <translation>この医学のファイルにはよりも 1 つのメッシュが含まれています。</translation>
    </message>
    <message>
      <source>HOM_MED_FILE_4</source>
      <translation>音楽配信マック ＆ ファイルのメッシュを読み取れませんでした。</translation>
    </message>
    <message>
      <source>HOM_MED_FILE_5</source>
      <translation>この医学のファイルには、フィールドが含まれていません。</translation>
    </message>
    <message>
      <source>HOM_MED_FILE_6</source>
      <translation>医学ファイル （秒） （秒） フィールドを読み取ることができません。</translation>
    </message>
    <message>
      <source>HOM_SELECT_STUDY</source>
      <translation>研究医 associe\n のファイルを選択または医学ファイルを選択します。</translation>
    </message>
    <message>
      <source>HOM_CASE_NAME</source>
      <translation>場合に名前を付ける必要があります。</translation>
    </message>
    <message>
      <source>HOM_CASE_DIRECTORY_1</source>
      <translation>1 つの場合を動作するようにディレクトリを選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_CASE_DIRECTORY_2</source>
      <translation>このディレクトリは、既に使用中です。</translation>
    </message>
    <message>
      <source>HOM_CASE_DIRECTORY_3</source>
      <translation>有効なディレクトリを選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_CASE_DIRECTORY_4</source>
      <translation>HOM_CASE_DIRECTORY_4</translation>
    </message>
    <message>
      <source>HOM_CASE_MESH</source>
      <translation>1 つは、初期のメッシュを選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_CASE_GROUP</source>
      <translation>グループ"%1"は、以上の境界線に割り当てることはできません。</translation>
    </message>
    <message>
      <source>HOM_CASE_EDIT_WINDOW_TITLE</source>
      <translation>場合の編集</translation>
    </message>
    <message>
      <source>HOM_CASE_EDIT_STATE_0</source>
      <translation>HOM_CASE_EDIT_STATE_0</translation>
    </message>
    <message>
      <source>HOM_CASE_EDIT_STATE</source>
      <translation>HOM_CASE_EDIT_STATE</translation>
    </message>
    <message>
      <source>HOM_CASE_PURSUE_WINDOW_TITLE</source>
      <translation>HOM_CASE_PURSUE_WINDOW_TITLE</translation>
    </message>
    <message>
      <source>HOM_ITER_NAME</source>
      <translation>名前を反復処理する必要があります。</translation>
    </message>
    <message>
      <source>HOM_ITER_STARTING_POINT</source>
      <translation>これは、前のイテレーションを指定する必要があります。</translation>
    </message>
    <message>
      <source>HOM_ITER_MESH</source>
      <translation>最終的なメッシュの名前。</translation>
    </message>
    <message>
      <source>HOM_ITER_HYPO</source>
      <translation>仮説を選択します。</translation>
    </message>
    <message>
      <source>HOM_ITER_FIELD_FILE</source>
      <translation>この前提には、ファイルのフィールドを指定する必要があります。</translation>
    </message>
    <message>
      <source>HOM_ITER_STARTING_POINT_0</source>
      <translation>メッシュ</translation>
    </message>
    <message>
      <source>HOM_ITER_STARTING_POINT_1</source>
      <translation>初期のイテレーションの場合</translation>
    </message>
    <message>
      <source>HOM_ITER_STARTING_POINT_2</source>
      <translation>HOM_ITER_STARTING_POINT_2</translation>
    </message>
    <message>
      <source>HOM_ITER_EDIT_WINDOW_TITLE</source>
      <translation>イテレーションの編集</translation>
    </message>
    <message>
      <source>HOM_HYPO_NAME</source>
      <translation>仮説に名前を付ける必要があります。</translation>
    </message>
    <message>
      <source>HOM_HYPO_FIELD_FILE</source>
      <translation>それはフィールドのファイルを提供する必要があります。</translation>
    </message>
    <message>
      <source>HOM_HYPO_ZONE_1</source>
      <translation>ゾーンを選択します。</translation>
    </message>
    <message>
      <source>HOM_HYPO_ZONE_2</source>
      <translation>1 つは、少なくとも 1 つのゾーンを選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_HYPO_ZONE_3</source>
      <translation>洗練された、または deraffinement、両方ではないです。</translation>
    </message>
    <message>
      <source>HOM_HYPO_NORM_L2</source>
      <translation>標準の L2</translation>
    </message>
    <message>
      <source>HOM_HYPO_NORM_INF</source>
      <translation>無限の標準</translation>
    </message>
    <message>
      <source>HOM_HYPO_NORM_ABS</source>
      <translation>絶対値</translation>
    </message>
    <message>
      <source>HOM_HYPO_NORM_REL</source>
      <translation>関係</translation>
    </message>
    <message>
      <source>HOM_HYPO_COMP</source>
      <translation>1 つ以上のコンポーネントを選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_HYPO_EDIT_WINDOW_TITLE</source>
      <translation>仮説の編集</translation>
    </message>
    <message>
      <source>HOM_ZONE_NAME</source>
      <translation>領域に名前を必要があります。</translation>
    </message>
    <message>
      <source>HOM_ZONE_LIMIT</source>
      <translation>最大 %1 は %1 のミニよりも大きい必要があります。</translation>
    </message>
    <message>
      <source>HOM_ZONE_RAYON</source>
      <translation>外側の半径は、内側の半径よりも大きい必要があります。</translation>
    </message>
    <message>
      <source>HOM_ZONE_EDIT_WINDOW_TITLE</source>
      <translation>領域の編集</translation>
    </message>
    <message>
      <source>HOM_BOUN_NAME</source>
      <translation>名前の国境に与えする必要があります。</translation>
    </message>
    <message>
      <source>HOM_BOUN_MESH</source>
      <translation>1 つの枠を含むメッシュを選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_BOUN_CASE</source>
      <translation>場合ファイルのメッシュが知られています。</translation>
    </message>
    <message>
      <source>HOM_AXE</source>
      <translation>軸は、ゼロ以外のベクトルでなければなりません。</translation>
    </message>
    <message>
      <source>HOM_BOUN_A_EDIT_WINDOW_TITLE</source>
      <translation>分析のフロンティアの編集</translation>
    </message>
    <message>
      <source>HOM_BOUN_D_EDIT_WINDOW_TITLE</source>
      <translation>離散境界の編集</translation>
    </message>
    <message>
      <source>HOM_GROU_EDIT_WINDOW_TITLE</source>
      <translation>選択したグループ</translation>
    </message>
    <message>
      <source>HOM_MESH_INFO_0</source>
      <translation>HOM_MESH_INFO_0</translation>
    </message>
    <message>
      <source>HOM_MESH_INFO_1</source>
      <translation>HOM_MESH_INFO_1</translation>
    </message>
    <message>
      <source>HOM_MESH_INFO_2</source>
      <translation>HOM_MESH_INFO_2</translation>
    </message>
    <message>
      <source>HOM_YACS_EDIT_WINDOW_TITLE</source>
      <translation>HOM_YACS_EDIT_WINDOW_TITLE</translation>
    </message>
  </context>
</TS>
