c
c     texte pour l'information sur les entites
c
c                  1234567890123456789012345678901234567890
      textno(0) = 'C''est un noeud isole.                   '
      textno(1) = 'C''est un sommet d''arete.                '
      textno(2) = 'C''est un milieu d''arete (noeud P2).     '
      textno(3) = 'C''est un support de maille-point.       '
      textno(5) = 'Il n''existe pas                         '
      textno(7) = 'C''est un noeud d''une maille ignoree.    '
c
c                  1234567890123456789012345678901234567890
      textmp(0) = 'Active                                  '
      textmp(5) = 'Elle n''existe pas                       '
c
c                  1234567890123456789012345678901234567890
      textar(0) = 'Active                                  '
      textar(2) = 'Mere de deux actives                    '
      textar(5) = 'Elle n''existe pas                       '
      textar(9) = 'Mere d''inactive(s)                      '
c
      texttr(0) = 'Actif                                   '
      texttr(1) = 'Coupe en deux par l''arete numero 1      '
      texttr(2) = 'Coupe en deux par l''arete numero 2      '
      texttr(3) = 'Coupe en deux par l''arete numero 3      '
      texttr(4) = 'Pere de quatre actifs                   '
      texttr(5) = 'Il n''existe pas                         '
      texttr(6) = 'Coupe en 2 par l''arete nro 1 basculee   '
      texttr(7) = 'Coupe en 2 par l''arete nro 2 basculee   '
      texttr(8) = 'Coupe en 2 par l''arete nro 3 basculee   '
      texttr(9) = 'Pere d''inactif(s)                       '
c
c                  1234567890123456789012345678901234567890
      textqu( 0) = 'Actif                                   '
      textqu( 4) = 'Pere de quatre actifs                   '
      textqu(55) = 'Il n''existe pas                        '
      textqu(99) = 'Pere d''inactif(s)                       '
      textqu(21) = 'Coupe en 2 quad. par les aretes 1 et 3  '
      textqu(22) = 'Coupe en 2 quad. par les aretes 2 et 4  '
      textqu(31) = 'Coupe en 3 triangles par l''arete 1      '
      textqu(32) = 'Coupe en 3 triangles par l''arete 2      '
      textqu(33) = 'Coupe en 3 triangles par l''arete 3      '
      textqu(34) = 'Coupe en 3 triangles par l''arete 4      '
      textqu(41) = 'Coupe en 3 quad. par les aretes 1 et 2  '
      textqu(42) = 'Coupe en 3 quad. par les aretes 2 et 3  '
      textqu(43) = 'Coupe en 3 quad. par les aretes 3 et 4  '
      textqu(44) = 'Coupe en 3 quad. par les aretes 4 et 1  '
c
c                   1234567890123456789012345678901234567890
      textte( 0) = 'Actif                                   '
      textte(21) = 'Coupe en deux par l''arete numero 1      '
      textte(22) = 'Coupe en deux par l''arete numero 2      '
      textte(23) = 'Coupe en deux par l''arete numero 3      '
      textte(24) = 'Coupe en deux par l''arete numero 4      '
      textte(25) = 'Coupe en deux par l''arete numero 5      '
      textte(26) = 'Coupe en deux par l''arete numero 6      '
      textte(41) = 'Coupe en quatre par le triangle numero 1'
      textte(42) = 'Coupe en quatre par le triangle numero 2'
      textte(43) = 'Coupe en quatre par le triangle numero 3'
      textte(44) = 'Coupe en quatre par le triangle numero 4'
      textte(45) = 'Coupe en quatre par la diagonale 1-6    '
      textte(46) = 'Coupe en quatre par la diagonale 2-5    '
      textte(47) = 'Coupe en quatre par la diagonale 3-4    '
      textte(55) = 'Il n''existe pas                         '
      textte(85) = 'Coupe en huit par la diagonale 1-6      '
      textte(86) = 'Coupe en huit par la diagonale 2-5      '
      textte(87) = 'Coupe en huit par la diagonale 3-4      '
      textte(99) = 'Pere d''inactif(s)                       '
c
c                   1234567890123456789012345678901234567890
      textpy( 0) = 'Active                                  '
      textpy(55) = 'Elle n''existe pas                       '
c
c                   1234567890123456789012345678901234567890
      texthe( 0) = 'Actif                                   '
      texthe( 5) = 'Il n''existe pas                         '
      texthe( 8) = 'Coupe en huit                           '
      texthe( 9) = 'Pere d''inactif(s)                       '
      texthe(41) = 'Coupe par la face 1                     '
      texthe(42) = 'Coupe par la face 2                     '
      texthe(43) = 'Coupe par la face 3                     '
      texthe(44) = 'Coupe par la face 4                     '
      texthe(45) = 'Coupe par la face 5                     '
      texthe(46) = 'Coupe par la face 6                     '
c
c                   1234567890123456789012345678901234567890
      textpe( 0) = 'Actif                                   '
      textpe( 1) = 'Coupe par l''arete 1                     '
      textpe( 2) = 'Coupe par l''arete 2                     '
      textpe( 3) = 'Coupe par l''arete 3                     '
      textpe( 4) = 'Coupe par l''arete 4                     '
      textpe( 5) = 'Coupe par l''arete 5                     '
      textpe( 6) = 'Coupe par l''arete 6                     '
      textpe(17) = 'Coupe par l''arete 7                     '
      textpe(18) = 'Coupe par l''arete 8                     '
      textpe(19) = 'Coupe par l''arete 9                     '
      textpe(21) = 'Coupe par les aretes 1 et 8             '
      textpe(22) = 'Coupe par les aretes 2 et 9             '
      textpe(23) = 'Coupe par les aretes 3 et 7             '
      textpe(24) = 'Coupe par les aretes 4 et 8            '
      textpe(25) = 'Coupe par les aretes 5 et 9             '
      textpe(26) = 'Coupe par les aretes 6 et 7             '
      textpe(31) = 'Coupe par les aretes 1 et 5             '
      textpe(32) = 'Coupe par les aretes 2 et 6             '
      textpe(33) = 'Coupe par les aretes 3 et 4             '
      textpe(34) = 'Coupe par les aretes 1 et 6            '
      textpe(35) = 'Coupe par les aretes 2 et 4             '
      textpe(36) = 'Coupe par les aretes 4 et 5             '
      textpe(43) = 'Coupe par la face 3                     '
      textpe(44) = 'Coupe par la face 4                     '
      textpe(45) = 'Coupe par la face 5                     '
      textpe(51) = 'Coupe par la face 1                     '
      textpe(52) = 'Coupe par la face 2                     '
      textpe(55) = 'Il n''existe pas                         '
      textpe(80) = 'Coupe en huit                           '
      textpe(99) = 'Pere d''inactif(s)                       '
c
c                   12345678901234567890123456789012345678901234567890
      textvo( 1) = 'Il borde le tetraedre :                           '
      textvo( 2) = 'Il borde les deux tetraedres :                    '
      textvo( 3) = 'Il borde l''hexaedre :                             '
      textvo( 4) = 'Il borde les deux hexaedres :                     '
      textvo( 5) = 'Il borde la pyramide :                            '
      textvo( 6) = 'Il borde les deux pyramides :                     '
      textvo( 7) = 'Il borde le pentaedre :                           '
      textvo( 8) = 'Il borde les deux pentaedres :                    '
      textvo(11) = 'Elle borde le tetraedre :                         '
      textvo(12) = 'Elle borde les tetraedres :                       '
      textvo(13) = 'Elle borde l''hexaedre :                           '
      textvo(14) = 'Elle borde les hexaedres :                        '
      textvo(15) = 'Elle borde la pyramide :                          '
      textvo(16) = 'Elle borde les pyramides :                        '
      textvo(17) = 'Elle borde le pentaedre :                         '
      textvo(18) = 'Elle borde les pentaedres :                       '
      textvo(21) = 'Il est un sommet pour le tetraedre :              '
      textvo(22) = 'Il est un sommet pour les tetraedres :            '
      textvo(23) = 'Il est un sommet pour l''hexaedre :                '
      textvo(24) = 'Il est un sommet pour les hexaedres :             '
      textvo(25) = 'Il est un sommet pour la pyramide :               '
      textvo(26) = 'Il est un sommet pour les pyramides :             '
      textvo(27) = 'Il est un sommet pour le pentaedre :              '
      textvo(28) = 'Il est un sommet pour les  pentaedres :           '
      textvo(31) = 'Il est le milieu d''un cote du tetraedre :         '
      textvo(32) = 'Il est le milieu d''un cote des tetraedres :       '
      textvo(33) =
     >            'Il est le milieu d''un cote de l''hexaedre :        '
      textvo(34) = 'Il est le milieu d''un cote des hexaedres :        '
      textvo(35) = 'Il est le milieu d''un cote de la pyramide :       '
      textvo(36) = 'Il est le milieu d''un cote des pyramides :        '
      textvo(37) = 'Il est le milieu d''un cote de pentaedre :         '
      textvo(38) = 'Il est le milieu d''un cote des pentaedres :       '
      textvo(41) = 'Il est voisin du tetraedre :                      '
      textvo(42) = 'Il est voisin des tetraedres :                    '
      textvo(43) = 'Il est voisin de l''hexaedre :                     '
      textvo(44) = 'Il est voisin des hexaedres :                     '
      textvo(45) = 'Il est voisin de la pyramide :                    '
      textvo(46) = 'Il est voisin des pyramides :                     '
      textvo(47) = 'Il est voisin du pentaedre :                      '
      textvo(48) = 'Il est voisin des  pentaedres :                   '
      textvo(51) = 'Elle est voisine du tetraedre :                   '
      textvo(52) = 'Elle est voisine des tetraedres :                 '
      textvo(53) = 'Elle est voisine de l''hexaedre :                  '
      textvo(54) = 'Elle est voisine des hexaedres :                  '
      textvo(55) = 'Elle est voisine de la pyramide :                 '
      textvo(56) = 'Elle est voisine des pyramides :                  '
      textvo(57) = 'Elle est voisine du pentaedre :                   '
      textvo(58) = 'Elle est voisine des  pentaedres :                '
c                   12345678901234567890123456789012345678901234567890
c
