c
      texte(1,4) = '(/,a,''Traitement du '',a,i8)'
      texte(1,5) = '(27("="),/,'' Parcours des '',a,/,27("="))'
      texte(1,6) = '(''Numero du joint a creer       :'',i6)'
      texte(1,7) = '(''Nombre de creations de '',a,''    :'',i8)'
      texte(1,8) = '(''Nombre de duplications de '',a,'' :'',i8)'
      texte(1,9) = '(''   ==> '',a,i8,'' a dupliquer.'')'
      texte(1,10) = '(''Nouveau nombre de '',a,'' :'',i8)'
      texte(1,11) = '(5x,''Nombre de '',a,'' a creer    :'',i8)'
      texte(1,12) = '(/,5x,''Nombre de joints simples'',12x,'':'',i8)'
      texte(1,13) = '(/,5x,''Nombre de joints triples'',12x,'':'',i8)'
      texte(1,14) = '(/,5x,''Nombre de joints quadruples'',9x,'':'',i8)'
      texte(1,15) = '(''Nouveau nombre de '',a,'' :'',i8)'
      texte(1,16) = '(''. Creation du '',a,i8,'', cote'',i3)'
      texte(1,17) = '(''     extremites '',6i8)'
      texte(1,18) = '(a,a,'' de famille :'',i4)'
      texte(1,19) = '(''Nombre de familles de '',a,'' :'',i8)'
      texte(1,20) = '(''. Caracteristiques :'',4i6)'
      texte(1,21) =
     >'(/,5x,''Nombre de joints ponctuels ordre '',i2,'' :'',i8)'
      texte(1,22) = '(/,5x,''Nombre de joints ponctuels       :'',i8)'
      texte(1,30) = '(''Famille MED du '',a,i10,'' :'',i4)'
c
      texte(2,4) = '(/,a,''Treatment of the '',a,i8)'
      texte(2,5) = '(''Treatment of the '',a)'
      texte(2,6) = '(''Creation of the junctions #'',i6)'
      texte(2,7) = '(''Number of creations of '',a,''    :'',i8)'
      texte(2,8) = '(''Number of duplications of '',a,'' :'',i8)'
      texte(2,9) = '(''   ==> '',a,i8,'' to duplicate.'')'
      texte(2,10) ='(''New number of'',a,'' :'',i8)'
      texte(2,11) = '(5x,''Number of '',a,'' to create :'',i8)'
      texte(2,12) = '(/,5x,''Number of simple junctions   :'',i8)'
      texte(2,13) = '(/,5x,''Number of triple junctions   :'',i8)'
      texte(2,14) = '(/,5x,''Number of 4order junctions   :'',i8)'
      texte(2,15) = '(''New number of'',a,'' :'',i8)'
      texte(2,16) = '(''. Creation of the '',a,i8,'', side'',i3)'
      texte(2,17) = '(''     ends '',6i8)'
      texte(2,18) = '(a,'' Family of the ''a,'' :'',i4)'
      texte(2,19) = '(''Number of families of '',a,'' :'',i8)'
      texte(2,20) = '(''. Characteristics :'',4i6)'
      texte(2,21) = '(/,5x,''Number of nodal junctions    :'',i8)'
      texte(2,22) = '(/,5x,''Number of nodal junctions    :'',i8)'
      texte(2,30) = '(''MED family of the '',a,i10,'':'',i4)'
