c
      texte(1,4) = '(/,a6,'' LECTURE DES OPTIONS'')'
      texte(1,5) = '(26(''=''),/)'
      texte(1,6) ='(''Option associee au mot-cle '',a8)'
      texte(1,7) = '(''Illisible.'')'
      texte(1,8) = '(''Defini plusieurs fois.'')'
      texte(1,9) = '(''==> Valeur :'',i8)'
      texte(1,10) = '(''==> Valeur :'',g15.7)'
      texte(1,11) = '(''==> Valeur :'',a)'
c
      texte(2,4) = '(/,a6,'' READINGS OF OPTIONS'')'
      texte(2,5) = '(26(''=''),/)'
      texte(2,6) = '(''Option related to keyword '',a8)'
      texte(2,7) = '(''Unreadable.'')'
      texte(2,8) = '(''Multiple definition.'')'
      texte(2,9) = '(''==> Value :'',i8)'
      texte(2,10) = '(''==> Value :'',g15.7)'
      texte(2,11) = '(''==> Value :'',a)'
